name: continous-integration
on: [push]
jobs:

  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GH repository
        uses: actions/checkout@master

      - name: Get banana script
        run: curl https://raw.githubusercontent.com/Epitech/coding-style-checker/main/coding-style.sh -o /tmp/coding-style.sh; chmod +x /tmp/coding-style.sh

      - name: Run coding style checker
        run: /tmp/coding-style.sh . .

      - name: Display banana report
        run: cat coding-style-reports.log

      - name: Report banana result
        run: |
          NB_ERROR=$(cat coding-style-reports.log | wc -l)
          if [ $NB_ERROR -gt 0 ]; then
            ERRORS=$(cat coding-style-reports.log);
            echo "Banana found $NB_ERROR error(s)"
            echo "$ERRORS"
            exit 1
          fi
          echo "Everything is good ! Keep on coding !"
          exit 0

  compile:
    name: Compule project
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GH repository
        uses: actions/checkout@master

      - name: Compile project
        run: make

      - name: Check binary presence
        run: |
          if [ ! -f ./swapupcase]; then
            echo "Binary not found"
            exit 1
          fi
          echo "Binary found"
          exit 0

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: [compile, coding-style]
    steps:

      - name: Checkout GH repository
        uses: actions/checkout@master

      - name: Compile unit_tests
        run: make compile_tests

      - name: Run unit_tests
        run: ./unit_testing

      - name: Run integration tests
        run: ./integration_testing